server:
  port: 80
microservice:
  host:
   port: 1009
  #通讯协议，http,netty,http,jetty,socket,rmi,hessian,
  #redis,restful,webservice,mq等等
  protocol: 
   channel: redis
   #redis 配置，当microservice.protocol=redis时候
   redis:  
    address: 127.0.0.1
    port: 6379
   #mq 配置，当microservice.protocol=mq时候
   rabbit: 
    address: 127.0.0.1
    port: 2181
    username: mqtest
    password: 123456
   #restful 配置，当microservice.protocol=restful时候
   restful:  
    scannerPackage: com.microservice.restful.api
  registry:
    zookeeper:
      host: 
       address: 127.0.0.1
       port: 2181