server:
  port: 81
microservice:
  provider:
   address: 172.18.56.153:1009
  #通讯协议，netty
           #http
           #jetty
           #socket
           #rmi
           #redis
           #mq
      #以下三种比较特殊
           #hessian
           #restful
           #webservice(cxf实现)
  protocol: 
   channel: http
   #redis 配置，当microservice.protocol=redis时候
   redis:  
    address: 127.0.0.1
    port: 6379
   #mq 配置，当microservice.protocol=mq时候
   rabbit: 
    address: 127.0.0.1
    port: 5672
    username: mqtest
    password: 123456
  registry:
    zookeeper:
      host: 
       address: 127.0.0.1
       port: 2181
  #客户端扫描生成代理类
  remoteClientScan:
    basePackages: com.common.microservice.example.common.api,com.common.microservice.example.hessian.api,com.common.microservice.example.cxf.api,com.common.microservice.example.rest.api